# Generated by Django 4.2.5 on 2023-10-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.CharField(max_length=500, verbose_name='Subtitle'),
        ),
    ]
